import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { app } from '../src/app.js';
import { prisma } from '../src/lib/prisma.js';
describe('API endpoints',()=>{
  let server: ReturnType<typeof app.listen>;let base='';let token='';const testEmail=`integration-${Date.now()}@example.invalid`;
  beforeAll(()=>{server=app.listen(0);const address=server.address();if(!address||typeof address==='string')throw new Error('No test port');base=`http://127.0.0.1:${address.port}/api/v1`;});
  afterAll(async()=>{server.close();await prisma.user.deleteMany({where:{email:testEmail}});});
  it('returns the API index',async()=>{const response=await fetch(base);expect(response.status).toBe(200);expect((await response.json()).name).toBe('GadgetHub API');});
  it('returns healthy status',async()=>{const response=await fetch(`${base}/health`);expect(response.status).toBe(200);expect((await response.json()).status).toBe('healthy');});
  it('describes database-backed authentication and rejects browser GET login',async()=>{const service=await fetch(`${base}/auth`);expect(service.status).toBe(200);expect((await service.json()).persistence.users).toBe('User table');const loginGet=await fetch(`${base}/auth/login`);expect(loginGet.status).toBe(405);expect(loginGet.headers.get('allow')).toBe('POST');});
  it('serves catalogue and public content',async()=>{const [products,categories,faqs]=await Promise.all([fetch(`${base}/products`),fetch(`${base}/catalog/categories`),fetch(`${base}/content/faqs`)]);expect(products.status).toBe(200);expect(categories.status).toBe(200);expect(faqs.status).toBe(200);});
  it('does not pretend unconfigured AI is active',async()=>{const registration=await fetch(`${base}/auth/register`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:testEmail,password:'IntegrationPass123!',firstName:'Integration',lastName:'Test'})});expect(registration.status).toBe(201);token=(await registration.json()).token;const openAiKey=process.env.OPENAI_API_KEY;const deepSeekKey=process.env.DEEPSEEK_API_KEY;delete process.env.OPENAI_API_KEY;delete process.env.DEEPSEEK_API_KEY;try{const assistant=await fetch(`${base}/assistant/chat`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({message:'Help me choose a phone'})});expect(assistant.status).toBe(503);}finally{if(openAiKey)process.env.OPENAI_API_KEY=openAiKey;if(deepSeekKey)process.env.DEEPSEEK_API_KEY=deepSeekKey;}});
  it('persists a registration and authenticates it',async()=>{const stored=await prisma.user.findUnique({where:{email:testEmail}});expect(stored?.passwordHash).not.toBe('IntegrationPass123!');const login=await fetch(`${base}/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:testEmail,password:'IntegrationPass123!'})});expect(login.status).toBe(200);token=(await login.json()).token;const me=await fetch(`${base}/auth/me`,{headers:{authorization:`Bearer ${token}`}});expect(me.status).toBe(200);});
  it('revokes the authenticated session on logout',async()=>{const logout=await fetch(`${base}/auth/logout`,{method:'POST',headers:{authorization:`Bearer ${token}`}});expect(logout.status).toBe(204);const me=await fetch(`${base}/auth/me`,{headers:{authorization:`Bearer ${token}`}});expect(me.status).toBe(401);});
});
