import nodemailer from 'nodemailer';import twilio from 'twilio';import webpush from 'web-push';import crypto from 'node:crypto';import {S3Client,PutObjectCommand} from '@aws-sdk/client-s3';import {getSignedUrl} from '@aws-sdk/s3-request-presigner';import {AppError} from './http.js';import {prisma} from './prisma.js';
const env=process.env;const required=(names:string[])=>names.every(n=>!!env[n]);
export const providerHealth=()=>({email:env.EMAIL_ENABLED!=='false'&&required(['SMTP_HOST','SMTP_USER','SMTP_PASSWORD','EMAIL_FROM']),sms:required(['TWILIO_ACCOUNT_SID','TWILIO_AUTH_TOKEN','TWILIO_SMS_FROM']),whatsapp:required(['TWILIO_ACCOUNT_SID','TWILIO_AUTH_TOKEN','TWILIO_WHATSAPP_FROM']),paynow:required(['PAYNOW_INTEGRATION_ID','PAYNOW_INTEGRATION_KEY']),push:required(['VAPID_PUBLIC_KEY','VAPID_PRIVATE_KEY','VAPID_SUBJECT']),storage:required(['S3_REGION','S3_BUCKET','S3_ACCESS_KEY_ID','S3_SECRET_ACCESS_KEY']),cloudinary:required(['CLOUDINARY_CLOUD_NAME','CLOUDINARY_API_KEY','CLOUDINARY_API_SECRET']),ai:required(['DEEPSEEK_API_KEY']),webhooks:required(['WEBHOOK_SECRET'])});
export async function sendEmail(to:string,subject:string,text:string){if(!providerHealth().email)throw new AppError(503,'Email provider is not configured');const transport=nodemailer.createTransport({host:env.SMTP_HOST,port:Number(env.SMTP_PORT??587),secure:Number(env.SMTP_PORT)===465,auth:{user:env.SMTP_USER,pass:env.SMTP_PASSWORD}});return transport.sendMail({from:env.EMAIL_FROM,to,subject,text});}
const twilioClient=()=>twilio(env.TWILIO_ACCOUNT_SID!,env.TWILIO_AUTH_TOKEN!);
export async function sendSms(to:string,body:string){if(!providerHealth().sms)throw new AppError(503,'SMS provider is not configured');return twilioClient().messages.create({from:env.TWILIO_SMS_FROM!,to,body});}
export async function sendWhatsapp(to:string,body:string){if(!providerHealth().whatsapp)throw new AppError(503,'WhatsApp provider is not configured');return twilioClient().messages.create({from:`whatsapp:${env.TWILIO_WHATSAPP_FROM!.replace('whatsapp:','')}`,to:`whatsapp:${to.replace('whatsapp:','')}`,body});}
export async function startPhoneVerification(to:string,channel:'sms'|'whatsapp'='sms'){if(!env.TWILIO_VERIFY_SERVICE_SID)throw new AppError(503,'Twilio Verify is not configured');return twilioClient().verify.v2.services(env.TWILIO_VERIFY_SERVICE_SID).verifications.create({to,channel});}
export async function checkPhoneVerification(to:string,code:string){if(!env.TWILIO_VERIFY_SERVICE_SID)throw new AppError(503,'Twilio Verify is not configured');return twilioClient().verify.v2.services(env.TWILIO_VERIFY_SERVICE_SID).verificationChecks.create({to,code});}
export async function sendPush(userId:string,payload:object){if(!providerHealth().push)throw new AppError(503,'Push provider is not configured');webpush.setVapidDetails(env.VAPID_SUBJECT!,env.VAPID_PUBLIC_KEY!,env.VAPID_PRIVATE_KEY!);const subs=await prisma.pushSubscription.findMany({where:{userId}});const results=await Promise.allSettled(subs.map(s=>webpush.sendNotification({endpoint:s.endpoint,keys:{p256dh:s.p256dh,auth:s.auth}},JSON.stringify(payload))));return {sent:results.filter(x=>x.status==='fulfilled').length,failed:results.filter(x=>x.status==='rejected').length};}
export async function signedUpload(key:string,contentType:string){if(!providerHealth().storage)throw new AppError(503,'Object storage is not configured');const client=new S3Client({region:env.S3_REGION!,endpoint:env.S3_ENDPOINT||undefined,forcePathStyle:!!env.S3_ENDPOINT,credentials:{accessKeyId:env.S3_ACCESS_KEY_ID!,secretAccessKey:env.S3_SECRET_ACCESS_KEY!}});const safe=`uploads/${Date.now()}-${key.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const uploadUrl=await getSignedUrl(client,new PutObjectCommand({Bucket:env.S3_BUCKET!,Key:safe,ContentType:contentType}),{expiresIn:300});const publicUrl=env.S3_ENDPOINT?`${env.S3_ENDPOINT}/${env.S3_BUCKET}/${safe}`:`https://${env.S3_BUCKET}.s3.${env.S3_REGION}.amazonaws.com/${safe}`;return {uploadUrl,publicUrl,key:safe,expiresIn:300};}
export function signedCloudinaryAvatar(userId:string){if(!providerHealth().cloudinary)throw new AppError(503,'Cloudinary is not configured');const timestamp=Math.floor(Date.now()/1000);const folder='gadgethub/avatars';const publicId=`user-${userId}`;const signature=crypto.createHash('sha1').update(`folder=${folder}&overwrite=true&public_id=${publicId}&timestamp=${timestamp}${env.CLOUDINARY_API_SECRET}`).digest('hex');return {timestamp,folder,publicId,signature,apiKey:env.CLOUDINARY_API_KEY,cloudName:env.CLOUDINARY_CLOUD_NAME,uploadUrl:`https://api.cloudinary.com/v1_1/${env.CLOUDINARY_CLOUD_NAME}/image/upload`};}
