import { Router } from 'express';import { Role } from '@prisma/client';import { z } from 'zod';import { prisma } from '../lib/prisma.js';import { asyncHandler,validate } from '../lib/http.js';import { authenticate,authorize } from '../middleware/auth.js';
export const adminRouter=Router();adminRouter.use(authenticate,authorize(Role.STORE_MANAGER,Role.SUPER_ADMIN));
adminRouter.get('/dashboard',asyncHandler(async(_q,r)=>{const [customers,products,orders,pendingOrders,pendingPayments,pendingTradeIns,pendingRepairs,pendingReturns,sales]=await prisma.$transaction([prisma.user.count({where:{role:'CUSTOMER'}}),prisma.product.count(),prisma.order.count(),prisma.order.count({where:{status:{notIn:['DELIVERED','CANCELLED']}}}),prisma.payment.count({where:{status:{in:['PENDING','PROCESSING']}}}),prisma.tradeIn.count({where:{status:{in:['SUBMITTED','REVIEWING']}}}),prisma.repairRequest.count({where:{status:{notIn:['RESOLVED','CLOSED','REJECTED']}}}),prisma.returnRequest.count({where:{status:{in:['OPEN','IN_PROGRESS']}}}),prisma.order.aggregate({where:{status:'DELIVERED'},_sum:{total:true},_count:true})]);r.json({customers,products,orders,pendingOrders,pendingPayments,pendingTradeIns,pendingRepairs,pendingReturns,totalSales:sales._count,totalRevenue:sales._sum.total??0});}));
adminRouter.get('/reports/sales',asyncHandler(async(q,r)=>{const from=q.query.from?new Date(String(q.query.from)):new Date(Date.now()-30*86400000);const orders=await prisma.order.findMany({where:{createdAt:{gte:from},status:{not:'CANCELLED'}},include:{items:true,payments:true}});const daily=Object.values(orders.reduce<Record<string,{date:string;orders:number;revenue:number}>>((a,o)=>{const d=o.createdAt.toISOString().slice(0,10);a[d]??={date:d,orders:0,revenue:0};a[d].orders++;a[d].revenue+=Number(o.total);return a;},{}));r.json({from,summary:{orders:orders.length,revenue:orders.reduce((s,o)=>s+Number(o.total),0)},daily});}));
adminRouter.get('/reports/products',asyncHandler(async(_q,r)=>r.json(await prisma.product.findMany({orderBy:{viewCount:'desc'},take:50,include:{_count:{select:{orderItems:true,views:true,reviews:true}},brand:true,category:true}}))));
adminRouter.get('/reports/inventory',asyncHandler(async(_q,r)=>r.json(await prisma.inventory.findMany({include:{variant:{include:{product:true}},movements:{take:10,orderBy:{createdAt:'desc'}}}}))));
adminRouter.get('/reports/operations',asyncHandler(async(_q,r)=>{const [tradeIns,repairs,returns,payments,deliveries,loyalty]=await prisma.$transaction([prisma.tradeIn.groupBy({by:['status'],orderBy:{status:'asc'},_count:true}),prisma.repairRequest.groupBy({by:['status'],orderBy:{status:'asc'},_count:true}),prisma.returnRequest.groupBy({by:['status'],orderBy:{status:'asc'},_count:true}),prisma.payment.groupBy({by:['status'],orderBy:{status:'asc'},_count:true,_sum:{amount:true}}),prisma.delivery.groupBy({by:['status'],orderBy:{status:'asc'},_count:true}),prisma.loyaltyTransaction.aggregate({_sum:{points:true},_count:true})]);r.json({tradeIns,repairs,returns,payments,deliveries,loyalty});}));
adminRouter.get('/users',asyncHandler(async(_q,r)=>r.json(await prisma.user.findMany({select:{id:true,email:true,phone:true,firstName:true,lastName:true,role:true,isActive:true,createdAt:true,loyaltyPoints:true}}))));
adminRouter.patch('/users/:id',authorize(Role.SUPER_ADMIN),asyncHandler(async(q,r)=>r.json(await prisma.user.update({where:{id:String(q.params.id)},data:validate(z.object({role:z.nativeEnum(Role).optional(),isActive:z.boolean().optional()}),q.body),select:{id:true,email:true,role:true,isActive:true}}))));
adminRouter.get('/audit-logs',authorize(Role.SUPER_ADMIN),asyncHandler(async(_q,r)=>r.json(await prisma.auditLog.findMany({take:200,orderBy:{createdAt:'desc'}}))));

